Basic graphics with sample map. Can rotate on arrows
myxo/ascii_doom pull request #10
Opened 2020-07-12 13:58 UTC by TheBlek

2020-07-12 22:51 UTC, myxo commented
Сделай файлы render.{h, c} и вынеси туда работу с рендером карты.

2020-07-12 22:54 UTC, myxo commented
Сейчас скорость игрока неявно зависит от мощности компьютера (сколько раз может быть вызвана функция update, на мощных вызывается чаще). Чтобы это обойти в обновлении позиции игрока нужно использовать elapsed_time

2020-07-12 23:08 UTC, myxo commented
Давай теперь избавимся от этого кислотного цвета =) Пусть стены будут белыми. А пол закрасим разными символами в зависимости от от дальности. Можно например использовать `X x - .` Примерно так
![2020-07-13_02-07-06](https://user-images.githubusercontent.com/2719353/87258638-c57e5a80-c4ad-11ea-81da-aa69e2cc63f0.png)

2020-07-13 05:32 UTC, TheBlek commented
@myxo Я сделал, и запушил, но создать новый PR я не могу. Я так понимаю, все коммиты собираются в этот, поэтому переименовал.

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +char map[8][8] = {
Сделай мапу чуть побольше, чтобы по ней ходить можно было

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +	if (olc_get_key(VK_ESCAPE).held) { // Esc
Удали плз `// Esc`, этот коммент больше не нужен

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +	tmp_x += right * player_speed * sin(player_angle + M_PI_2);
А чему у нас равен sin(angle + pi/2) ? =)
И назови переменную new_x, так чуть более понятно

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +	if (map[(int)tmp_x][(int)player_y] != '#')
Хорошо бы выделить это в отдельную функцию `int is_wall(double x, double y)` и использовать её. Тогда если у нас представление карты поменяется, не нужно будет править кучу мест

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +	//const char * hello_str = "Hello world";
Этот код нужно удалить

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +	}
Выдели плз эти строки в отдельную функцию, что-нибудь типа `handle_player_movement`

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +		player_angle += 0.02;
0.02 - тоже скорость и достойна отдельной переменной =) Можно назвать `player_angular_speed`

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +int Dbutton = 0x44;
Посмотрел [ascii таблицу](http://www.asciitable.com/), оказывается эти значения соответствуют кодам заглавных букв

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +	double y = player_y;
эти x, y можно определить прямо в теле цикла
distance тоже

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +			y += d_distance * cos(ray_angle);
sin, cos можно посчитать 1 раз вне цикла

2020-07-13 08:34 UTC, myxo commented on src/main_doom.c
> +		int num_of_wall_sym = height * (2 / (distance));
Будет проще читать, если определить переменные, например, `ceiling_level`, `floor_level`, и потом с цикле идти по ним
```
for (int i = ceiling_level; i < floor_level; i++) {...}
```

2020-07-13 09:34 UTC, myxo requested changes

2020-07-13 09:34 UTC, myxo commented on src/main_doom.c
> +	}
!

2020-07-13 09:34 UTC, myxo commented on src/render.c
> +void draw_screen(world_t world, int width, int height) {
тут world можно нужно по указателю, это тяжелый объект, а ты его копируешь.

2020-07-13 09:34 UTC, myxo commented on src/render.c
> +		char sym = '#';
Заметь, на моем скриншоте все стены из одного символа. Сейчас там небольшое месиво из стен и пола

2020-07-13 09:34 UTC, myxo commented on src/render.h
> +#define RENDER
у нас принято `RENDER_H_`

2020-07-13 09:34 UTC, myxo commented on src/render.h
> +char map[16][16];
думаю её нужно пихнуть в world_t

2020-07-13 09:34 UTC, myxo commented on src/render.h
> +void draw_screen(world_t world, int width, int height);
На самом деле `width` и `height` не обязательно передавать. Их можно получить из olc_screen_* функций

2020-07-13 09:40 UTC, TheBlek commented on src/render.c
> +		char sym = '#';
Вы же сами просили градацию цвета для стен. Я сделал по аналогии с полом

2020-07-13 10:13 UTC, myxo approved these changes

2020-07-13 10:13 UTC, merged