Basic gun
myxo/ascii_doom pull request #21
Opened 2020-07-13 14:49 UTC by ruca905

2020-07-13 17:58 UTC, myxo requested changes

2020-07-13 17:58 UTC, myxo commented on src/world_object.c
> +        if (pow(x - world_global->bullet_array.array[i].pos.x, 2) + pow(y - world_global->bullet_array.array[i].pos.y, 2) <= pow(world_global->bullet_array.array[i].radius, 2)){
Длинный if. Разбей на несколько строчек или введи доп. переменные

2020-07-13 17:58 UTC, myxo commented on src/world_object.c
> +    world_global->bullet_array.array = malloc(world_global->bullet_array.capacity * sizeof(bullet_t));
Вынеси в отдельную функцию `init_bullet_array`

2020-07-13 17:58 UTC, myxo commented on src/render.c
> +        //}
Этот код должен быть в отдельной функции `draw_bullet`

2020-07-13 17:58 UTC, myxo commented on src/render.c
> +        //}
И в принципе тут должен быть несколько другой подход. Для рендера стен нам нужно просканировать все в поле нашего зрения потому-что нам нужно их рисовать с учетом перспективы. Для пуль этого делать не нужно. Нужно просто пробежаться по массиву пуль и отрисовать все (посчитав расстояние до неё и вычислив размер в экранных координатах)

2020-07-13 17:58 UTC, myxo commented on src/main_doom.c
> +    world->bullet_array.array[world->bullet_array.len].pos = world->player.pos;
Нужно чуть-чуть продвинуть начальное положение пули, иначе при стрельбе она вначале занимает весь экран. Как будто из глаз стреляем

2020-07-13 17:58 UTC, myxo commented on src/main_doom.c
> +double space_delay = 0;
time_from_last_shot

2020-07-13 17:58 UTC, myxo commented on src/main_doom.c
> +int height =  100;
А это зачем?

2020-07-13 17:58 UTC, myxo commented on src/main_doom.c
> +    if (olc_get_key(VK_SPACE).held) {
тут по логике должно быть не `held`, а `pressed`

2020-07-13 17:58 UTC, myxo commented on src/main_doom.c
> +    }
Сделай новый файл bullet.{c, h} и убери новые функции туда

2020-07-14 05:43 UTC, ruca905 commented on src/render.c
> +        //}
Не понимаю, кроме расстояния до пули и размера в экранных координатах, нам для отрисовки пули требуется высчитать положение пули на экране(т.к. пуля двигается независимо от игрока). Именно поэтому мы пробегаемся по всем `ray_angle` и ищем там пули.

2020-07-14 05:46 UTC, ruca905 commented on src/main_doom.c
> +int height =  100;
У меня только с int `height =  100;` запускается. Забыл обратно вернуть.

2020-07-14 08:23 UTC, myxo approved these changes

2020-07-14 08:23 UTC, myxo commented on src/world_object.c
> +        double oy_vec = y - world_global->bullet_array.array[i].pos.y;
Ну вообще эти переменные - не вектора, это разница между конкретными координатами. Так что я бы их назвал `dx`, `dy`

2020-07-14 08:23 UTC, merged

2020-07-15 05:15 UTC, ruca905 commented
Есть идея на счёт поведения `enemy`