Basic mobs
myxo/ascii_doom pull request #36
Opened 2020-07-14 13:13 UTC by ruca905

Вообщем я сделал чтобы, когда `enemy` видит игрока, он подходит к нему. А когда не видит, просто гуляет по карте.

2020-07-14 22:49 UTC, myxo requested changes

2020-07-14 22:49 UTC, myxo commented on src/bullet.h
> +#define ENEMY_BULLET 1
Объявления define'ов действительно лучше, чем просто 1 или 0. Но давай сделаем ещё лучше
```
enum bullet_host_t {
    kBulletPlayer,
    kBulletEnemy
};
```
И тогда все функции будут принимать bullet_host_t

2020-07-14 22:49 UTC, myxo commented on src/world_object.c
> +    world_global->map_height = 16;
Функция `read_map_for_file` уже записывает правильные map_width и map_height

2020-07-14 22:49 UTC, myxo commented on src/world_object.c
> +    int y_floor = (int)y;
Как раз хотел, чтобы это кто-нибудь сделал. Но зачем новые переменные?

2020-07-14 22:49 UTC, myxo commented on src/world_object.c
> +    if (pow(dx, 2) + pow(dy, 2) <= pow(r, 2)) {
Давай уже сделаем какую-нибудь
```
int is_in_circle(pos_t p, pos_t circle_center, double radius)
```
А то у нас много дублирующего кода

2020-07-14 22:49 UTC, myxo commented on src/world_object.c
> +int is_enemy(double x, double y) {
Не очень очевидный интерфейс у функции (надо ещё догадаться, что возвращается индекс + 1), давай сделаем так
```
int is_enemy(double x, double y, int * enemy_index) {}
```
Если враг найдет, то возвращается 1, и в enemy_index записывается его индекс

2020-07-14 22:49 UTC, myxo commented on src/bullet.c
> +        if (is_player(world->bullet_array.array[i].pos.x, world->bullet_array.array[i].pos.y) && world->bullet_array.array[i].host == ENEMY_BULLET) {
Лучше уже в одном стиле писать. Давай как выше, `world->bullet_array.array[i].host == ENEMY_BULLET` внутренним if'ом

2020-07-14 22:49 UTC, myxo commented on src/enemy.c
> +    } while (is_wall(world->enemy_array.array[world->enemy_array.len].target.x, world->enemy_array.array[world->enemy_array.len].target.y));
Блин, длинноватые строчки получаются. Давай создадим тут переменные `target_x`, `pos_x`  и т.д., будем работать с ними, а потом запишем их ниже в `world->enemy_array.array[world->enemy_array.len]`

2020-07-14 22:49 UTC, myxo commented on src/enemy.c
> +    return x;
```C
return atan2(delta_x, delta_y);
```

2020-07-14 22:49 UTC, myxo commented on src/enemy.c
> +double get_angle_from_pos_to_angle(point_t pos, point_t target) {
Странно функция называется. `get_angle_to_pos`

2020-07-14 22:49 UTC, myxo commented on src/enemy.c
> +        if (angle_to_player > start_enemy_view_angle && angle_to_player < stop_enemy_view_angle) {
Давай немного отрефакторим внутренность этого if. А то сейчас не так просто разобраться что тут происходит.
Если я правильно понял, мы тут преследуем 2 цели: посчитать расстояние до игрока и проверить есть ли между ними стена (ну и в зависимости от этого сделать те или иные действия).
1) посчитать расстояние до игрока можно по формуле расстояния между двумя точками (и это неплохо было бы вынести в отдельную функцию)
2) Факт наличия стены лучше тоже вынести в отдельную функцию `int has_wall_between(pos_t p1, pos_t p2)`. Наверняка потом понадобится где-нибудь ещё. Плюс мне кажется это можно сделать эффективней, а оптимизировать алгоритм проще, если это отдельная функция

Кажется, что после этого логика будет яснее

2020-07-14 22:49 UTC, myxo commented on src/enemy.c
> +        world->enemy_array.array[i].angle = get_angle_from_pos_to_angle(world->enemy_array.array[i].pos, world->enemy_array.array[i].target);
Есть небольшая хитрость, чтобы не писать эти бесконечные строчки
```C
enemy_t * enemy = &world->enemy_array.array[i];
enemy->angle = get_angle_from_pos_to_angle(enemy->pos, enemy->target);
```

2020-07-14 22:49 UTC, myxo commented on src/enemy.c
> +            new_y += time_elapsed * world->enemy_array.array[i].speed * cos(world->enemy_array.array[i].angle);
Давайте уже сделаем функцию
```C
pos_t get_new_pos(pos_t cur_pos, double angle, double dist);
```

2020-07-14 22:49 UTC, myxo commented on src/enemy.c
> +        int check_move = 1;
лучше назвать `update_position`

2020-07-14 22:49 UTC, myxo commented on src/enemy.c
> +                } while (is_wall(world->enemy_array.array[i].target.x, world->enemy_array.array[i].target.y));
Тоже уже несколько раз встречается. В отдельную функцию
```C
pos_t get_rand_pos_on_floor(world_t* world);
```

2020-07-14 22:49 UTC, myxo commented on src/render.c
> +        }
В отдельную функцию `draw_enemies`. Кстати рисовку пуль тоже в отдельную функцию, я вроде уже просил об этом.

2020-07-14 22:49 UTC, myxo commented on src/render.c
> +                int bullet_height = 8 / 2 / distance;
А чего не `4 / distance` ?

2020-07-15 05:18 UTC, ruca905 commented
Есть идея на счёт поведения `enemy`
Как он двигается сейчас:
- если видит игрока, идёт к нему(пока `distance` до него >= 4)
- если не видит, то просто гуляет

Так вот, то как устроен процесс прогулки мне сейчас не очень нравится.

2020-07-15 05:29 UTC, ruca905 commented
Вообще, сам алгоритм нахождения кратчайшего пути в графе полученном из карты может быть полезен в дальнейшем, даже если мы придумаем другое поведение врагов.

2020-07-15 07:55 UTC, ruca905 commented
В данной ветке исправлена проблема с "Crash during shooting".

2020-07-15 08:19 UTC, ruca905 commented
О баге "Sometimes bullet is not fire":bullets_movement(world, time_elapsed*60);

2020-07-15 08:40 UTC, myxo commented
Сделал отдельный пункт по поведению enemy #43

2020-07-15 08:53 UTC, myxo requested changes

2020-07-15 08:53 UTC, myxo commented on src/world_object.c
> +    return pos;
Только сейчас функция не гарантирует, что точка будет `on_floor`, то есть сюда же нужно цикл добавить

2020-07-15 08:53 UTC, myxo commented on src/world_object.c
> +    pos.y = y;
Кстати вроде такая инициализация должна работать
```C
point_t pos = {x, y};
```

2020-07-15 08:53 UTC, myxo commented on src/world_object.c
>      return 0;
Не пишите конструкции 
```C
if (a == b) {
  return 1;
}
return 0;
```
Пишите
```C
return a == b;
```

2020-07-15 08:53 UTC, myxo commented on src/render.c
> +            if (is_enemy(x, y, &temp)) {
Кстати тоже довольно частый паттерн в таком случае, если не нужен индекс, то передаем NULL. Но естественно тогда функция `is_enemy` не должна записывать индекс, если передали NULL.

2020-07-15 12:18 UTC, myxo approved these changes

2020-07-15 12:18 UTC, merged