Added simple draw_sprite func. Since I can't take symbol from sprite I can't make transperency
myxo/ascii_doom pull request #48
Opened 2020-07-15 14:30 UTC by TheBlek

…I can't make transperency

2020-07-15 14:32 UTC, TheBlek commented
Пусть, наверно, пока просто повисит, подъедут символы в спрайты, я доработаю - запулим

2020-07-15 14:36 UTC, myxo commented on src/main_doom.c
>      display_watch();
Тест: будет ли slack бот показывать это сообщение.

2020-07-17 08:15 UTC, myxo requested changes

2020-07-17 08:15 UTC, myxo commented on src/render.c
> +                olc_draw(i, j, ch, col);
А где обновление zbuffer?

2020-07-17 08:20 UTC, merged