sprite editor corrections
myxo/ascii_doom pull request #55
Opened 2020-07-16 04:00 UTC by siw321

2020-07-16 10:45 UTC, myxo requested changes
Заметь, сейчас с твоими изменениями основной проект не компилится

2020-07-16 10:45 UTC, myxo commented on src/sprite.c
> +    fwrite(texture->glyphs, sizeof(char), len, file);
Дважды записывается

2020-07-16 10:45 UTC, myxo commented on src/sprite.h
> +
Функции
```C
short get_sprite_color(int x, int y, sprite_t* sprite);
short sample_sprite_color(double x, double y, sprite_t* sprite);
```
нужны. Именно их будет вызывать код рендеренга. Пусть пока они просто вызывают соответствующие функции у первой текстуры

2020-07-16 10:45 UTC, myxo commented on src/sprite.h
>  void load_sprite_from_file(const char* filename, sprite_t* sprite);
Я пока слабо представляю себе как мы именно будет сохранять/загружать спрайты. Давай отложим этот момент на будущее. Это функции пускай останутся, но давай сделаем функцию 
```C
void attach_texture_to_sprite(sprite_t * sprite, texture_t texture);
```
Которая добавляет текстуру в спрайту. То есть клиентский код будет примерно такой
```C
load_texture_from_file("texture.tx", texture1);
load_texture_from_file("texture.tx", texture2);
attach_texture_to_sprite(sprite, texture1);
attach_texture_to_sprite(sprite, texture2);
```

2020-07-17 08:56 UTC, myxo requested changes
По-прежнему нет функций `sample_sprite_color`. По прежнему не компилируется

2020-07-17 08:56 UTC, myxo commented on src/render.c
> -            world->z_buffer[row][i] = distance;
Удалил нужное.

2020-07-17 08:56 UTC, myxo commented on src/world_object.h
>  } game_textures_t;
Клиенты должны по-прежнему работать с спрайтами. Поэтому в добавок к текущим объектам со спрайтами должны быть добавлены объекты с текстурами

2020-07-17 08:56 UTC, myxo commented on src/sprite.c
> +    sprite->texture_size = sizeof(int) * 2 + sizeof(short) * len + sizeof(char) * len;
Если честно не понял что за size такой... Он должен быть равен количеству текстур в спрайте

2020-07-17 09:04 UTC, siw321 commented on src/sprite.c
> +    sprite->texture_size = sizeof(int) * 2 + sizeof(short) * len + sizeof(char) * len;
size должен быть равен размеру одной текстуры в байтах

2020-07-17 10:31 UTC, myxo requested changes

2020-07-17 10:31 UTC, myxo commented on src/sprite.c
> +    sprite->texture_size = sizeof(int) * 2 + sizeof(short) * len + sizeof(char) * len;
Нет. Тебе тут size не нужен. Память под сами данные текстуры выделяется самой текстурой. Здесь тебе нужна память `sizeof(texture_t) * n`

2020-07-17 10:31 UTC, myxo commented on src/sprite.c
> +void init_sprite(int width, int height, sprite_t* sprite) {
Спрайт в нашей терминологии - только хранилище текстур, ему не нужен размер

2020-07-17 10:31 UTC, myxo commented on src/main_doom.c
> +int height = 80;
!

2020-07-18 21:19 UTC, merged