Mob ai improvement
myxo/ascii_doom pull request #60
Opened 2020-07-17 04:22 UTC by ruca905

2020-07-18 22:24 UTC, myxo requested changes

2020-07-18 22:24 UTC, myxo commented on src/enemy.c
> +#include "../third_party/olc/olc.h"
`#include "olc/olc.h"`
Вот эта строчка в CMakeLists позволяет нам это делать
```
target_include_directories(ascii_doom PRIVATE third_party)
```

2020-07-18 22:24 UTC, myxo commented on third_party/olc/olcConsoleGameEngine.h
> +		{
@siw321 @Sobool @TheBlek @ruca905 Ещё раз скажу. Просматривайте свои изменения перед коммитом. Если изменения пустые (как тут), то их нужно откатить (если вы просматриваете в GUI, то там это делать легко, можно даже откатывать отдельные строчки кода). Потому-что теперь в истории olcConsoleGameEngine.h навсегда останется это изменение.

2020-07-18 22:24 UTC, myxo commented on src/world_object.c
> +    return 1;
Зачем? Нормально же было. К тому же ты неправильно изменил

2020-07-18 22:24 UTC, myxo commented on src/world_object.c
> +    world_global->player.angle_of_vision = M_PI_4;
Теперь это читается из конфига (и тут не нужно)

2020-07-18 22:24 UTC, myxo commented on src/structs_of_data.c
> +    } else
Надо хотя бы в одном if else сохранять стиль. Ну то есть добавь тут фигурные скобки, а то косо смотрится =)

2020-07-18 22:24 UTC, myxo commented on src/structs_of_data.c
> +    if (q.head == NULL)
`return q.head == NULL`

2020-07-18 22:24 UTC, myxo commented on src/enemy.c
> +        point_array_t point_near = init_point_array(8);
Вот эта память течет (да и вообще я тут нигде не вижу освобождения памяти)

2020-07-18 22:24 UTC, myxo commented on src/enemy.c
> +            for (int y = -1; y <= 1; y++) {
Проще сделать как-то так, а то такой цикл в голове раскрывать сложно
```C
int x_move[4] = {-1, 0,  0, 1};
int y_move[4] = { 0, 1, -1, 0};
for (int i = 0; i < 4; i++) {
    int x = cur.x + x_move[i];
    int y = cur.y + y_move[i];
    // ...
}
```

2020-07-18 22:24 UTC, myxo commented on src/enemy.c
> +        for (int i = 0; i < point_near.len; ++i) {
А ты не можешь сделать это прям в предыдущем цикле? Тогда и `point_near` не понадобится

2020-07-18 22:24 UTC, myxo commented on src/enemy.c
> +    for (point_t cur = enemy->global_target; !(cur.x == -1 && cur.y == -1); cur = pred[(int)cur.x][(int)cur.y]) {
FYI. У меня в этой строчке было падение. В `cur` был какой-то мусор

2020-07-18 22:24 UTC, myxo commented on src/enemy.c
> +                //if (to.x == enemy->global_target.x && to.y == enemy->global_target.y)
А отсюда не нужно выходить при закоменченном условии?

2020-07-18 22:24 UTC, myxo commented on src/enemy.c
> +                enemy->global_target = world->player.pos;
А если мы уйдем с этой позиции, бот будет идти к месту, в котором мы когда-то стояли?

2020-07-19 03:46 UTC, ruca905 commented on src/enemy.c
> +    for (point_t cur = enemy->global_target; !(cur.x == -1 && cur.y == -1); cur = pred[(int)cur.x][(int)cur.y]) {
Ну тут я могу только догадываться, скорее всего поиск в ширину не нашёл global_target, поэтому в `pred[(int)global_target.x][(int)global_target.y]` какой то мусор. Сделаю проверку на это

2020-07-19 03:51 UTC, ruca905 commented on src/enemy.c
> +                enemy->global_target = world->player.pos;
Так мы каждый update пересчитываем `path` к игроку, если видим его

2020-07-19 03:53 UTC, ruca905 commented on src/world_object.c
> +    return 1;
Честно сказать, я уже и сам не помню)

2020-07-19 03:54 UTC, ruca905 commented on third_party/olc/olcConsoleGameEngine.h
> +		{
А в терминале получается `git diff` это самое удобное что есть?

2020-07-19 10:47 UTC, myxo requested changes

2020-07-19 10:47 UTC, myxo commented on src/enemy.c
> +                    if (to.x == (int)enemy->global_target.x && to.y == (int)enemy->global_target.y) {
`to.x` `to.y` тоже к int нужно привести.
upd. Хотя даже проще использовать `x` и `y`, они и так инты

2020-07-19 10:47 UTC, myxo commented on src/enemy.c
> +                enemy->global_target = world->player.pos;
Хм... Может пересчитывать не каждый update, а если игрок сдвинулся?

2020-07-19 11:46 UTC, myxo approved these changes

2020-07-19 11:46 UTC, merged