crates with first aid and ammo
myxo/ascii_doom pull request #83
Opened 2020-07-19 14:04 UTC by siw321

После смерти моба остается ящик с бонусами.

2020-07-19 21:35 UTC, myxo requested changes
1. У меня этот код сейчас не компилится.
2. Пофикси конфликты
3. Опять огромный PR. Причем большая часть диффа в нем вообще не используется.
4. Самодеятельность - это хорошо. Но мы работаем в команде, поэтому изменения (или неясности) в постановке задачи нужно обсуждать. И если начал что-то делать, то хотя бы нормально это дело запрогать. Сейчас я вообще из кода не понимаю что происходит

2020-07-19 21:35 UTC, myxo commented on src/bullet.c
> +                enemy_hit(world, index, 34);
А почему так? Плюс сделать уже поле damage у bullet_t и передать сюда

2020-07-19 21:35 UTC, myxo commented on src/drop.c
> +void add_drop(world_t* world, point_t pos) {
Если честно, то вообще нифига не понятно что тут происходит. Что за новый `have_radar ` ?  Что за `type`, что за числа туда присваиваются? Почему переменная называется `tmp` и используется каким-то странным образом?

2020-07-19 21:35 UTC, myxo commented on src/drop.c
> +            world->player.health += 50;
Магические числа

2020-07-19 21:35 UTC, myxo commented on src/render.c
> +        world->player.health = world->player.maxhealth;
А это возможно?

2020-07-19 21:35 UTC, myxo commented on src/sprite.c
> +/* счетчик патронов
?

2020-07-19 21:35 UTC, myxo commented on src/drop.h
> +void add_drop(world_t* world, point_t pos);
В целом мне кажется, что более разумным будет, чтобы это появлялось не с убитых мобов, а рандомом по карте

2020-07-20 05:25 UTC, siw321 commented on src/render.c
> +        world->player.health = world->player.maxhealth;
Иногда, если подобрать аптечку.

2020-07-20 09:49 UTC, myxo requested changes

2020-07-20 09:49 UTC, myxo commented on src/drop.c
> +        if (world->player.health == world->player.maxhealth) {
Странная логика. Почему аптечка повышает патроны?

2020-07-20 09:49 UTC, myxo commented on src/drop.c
> +            if (world->player.health > world->player.maxhealth) {
Просто проверить, что мы не выходим за `maxhealth`

2020-07-20 09:49 UTC, myxo commented on src/drop.c
> +        world->player.bullets += 10;
Убрать магическое число в переменную

2020-07-20 09:49 UTC, myxo commented on src/drop.c
> +            world->player.health += 50;
Убрать магическое число в переменную

2020-07-20 09:49 UTC, myxo commented on src/drop.c
> +        if (distance_to_player <= 1) {
Убрать магическое число в переменную

2020-07-20 09:49 UTC, myxo commented on src/drop.h
> +    MAXHP = 5,
Почему они 4 и 5?
И в принципе убрать regen и maxhp. Они сейчас только усложнят геймплей

2020-07-20 09:49 UTC, myxo commented on src/enemy.c
> +    world->enemy_array.array[world->enemy_array.len].health = 100;
Убрать магическое число в переменную

2020-07-20 09:49 UTC, myxo commented on src/enemy.c
> +                    shoot_bullet(world, enemy->pos, angle_to_player, time_elapsed, kBulletEnemy, 34);
Убрать магическое число в переменную

2020-07-20 09:49 UTC, myxo commented on src/main_doom.c
> +    if (olc_get_key(VK_SPACE).held & get_world()->player.bullets > 0) {
Патроны должны быть свои для каждого оружия. Но чтобы не перегружать, пусть ammo kit увеличивает патроны активного оружия

2020-07-20 09:49 UTC, myxo commented on src/main_doom.c
> +    if (olc_get_key(VK_SPACE).held & get_world()->player.bullets > 0) {
Эта проверка должна быть внутри `shoot_from_active_weapon`

2020-07-20 09:49 UTC, myxo commented on src/main_doom.c
> +    if (get_world()->drop_array.len != 0) {
Эта проверка должна быть внутри `drop_check`

2020-07-20 09:49 UTC, myxo commented on src/main_doom.c
> +    get_world()->player.health += get_world()->player.regen * time_elapsed;
А почему эта строчка посреди вызовов функций рисовки?

2020-07-20 09:49 UTC, myxo commented on src/render.c
> +            draw_object(player, drop->pos, drop->radius, '+', FG_GREEN, 50);
Нужно рисовать текстурой

2020-07-20 09:49 UTC, myxo commented on src/render.c
> +        world->player.health = world->player.maxhealth;
Игровая логика должна запрещать такое

2020-07-20 10:39 UTC, myxo commented
Вообще с патронами возможно лучше сделать отдельно, так как ещё есть задача https://github.com/myxo/ascii_doom/issues/27 наверняка код будет пересекаться

2020-07-21 13:05 UTC, myxo requested changes
Не компилируется

2020-07-21 13:05 UTC, myxo commented on src/drop.c
> +    int rockets = 2;
нужно сделать не локальными переменными, а глобальными, в world_t. Причем должны читаться из конфига

2020-07-21 13:05 UTC, myxo commented on src/drop.c
> +        world->player.health += 50;
`heal `

2020-07-21 13:05 UTC, myxo commented on src/render.c
> +                world->z_buffer[row][i] = MAX_BUFF;
У нас есть полупрозрачные стены?

2020-07-21 13:05 UTC, myxo commented on src/render.c
> +                olc_draw(row, i, 'X', FG_GREEN);
Почему тут код, который не имеет отношения к пункту????

2020-07-21 13:05 UTC, myxo commented on src/render.c
> +void bullets_counter(world_t* world) {
`draw_bullets_counter`?

2020-07-21 13:05 UTC, myxo commented on src/render.c
> +        bullet = (world->weapon_list->pistol->bullets * width) / 20;
Магические числа

2020-07-21 13:05 UTC, myxo commented on src/render.c
> +        bullet = (world->weapon_list->rifle->bullets * width) / 50;
Магические числа

2020-07-21 13:05 UTC, myxo commented on src/render.c
> +        bullet = (world->weapon_list->rocket_launcher->bullets * width) / 10;
Магические числа

2020-07-21 13:05 UTC, myxo commented on src/render.c
> +                    get_world()->z_buffer[i][j] = obj.distance;
Ты этим изменением откатываешь баг фикс. Что-то не то

2020-07-21 13:05 UTC, myxo commented on src/render.h
> +void draw_sprite(sprite_t* sprite, int texture_index, point_t pos, double obj_radis, double obj_height);
Почему дважды повторяется?

2020-07-21 13:05 UTC, myxo commented on src/sprite.h
> +char sample_sprite_glyph(double x, double y, sprite_t* sprite, int texture_index);
Почему дважды повторяется?

2020-07-21 13:05 UTC, myxo commented on src/weapon.c
> -        *time_since_last_shot = 0;
Что-то не так с мерджем

2020-07-22 11:25 UTC, merged