Barrels
myxo/ascii_doom pull request #98
Opened 2020-07-21 09:10 UTC by TheBlek

2020-07-23 00:16 UTC, myxo requested changes
Нужно разрешить конфликты и добавить текстуру. В остальном ок

2020-07-23 00:16 UTC, myxo commented on src/render.c
> +        draw_object(player, barrel->pos, barrel->radius, '#', FG_RED, 60, FLOOR);
нужна текстура

2020-07-23 09:20 UTC, myxo approved these changes
Ещё есть замечания, нужно будет исправить в дальнейших PR

2020-07-23 09:20 UTC, myxo commented on src/world_object.c
> +        double y_float = (1 + rand() % 9) / 10.0;
Вообще ты можешь добиться такого же эффекта так
```C
double new_x = (rand() % (map_height * 10)) / 10.0
```

2020-07-23 09:20 UTC, myxo commented on src/world_object.c
>          int new_x = rand() % world_global->map_height;
Кстати, не перепутаны ли тут высота с шириной?
Падение из-за `is_wall` не будет, так что я сейчас мерджу, но нужно исправить

2020-07-23 09:21 UTC, merged

2020-07-24 10:13 UTC, TheBlek commented on src/world_object.c
> +        double y_float = (1 + rand() % 9) / 10.0;
Нет, тут фишка в том, что они не спавнятся на ровных координатах типа 3.00 4.00, я это сделал для того, чтобы они в стенах не появлялись